language: python
python:
    - "2.7"
install:
    - "wget -q https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.35.zip"
    - "unzip -q google_appengine_1.9.35.zip"
script:
    - "APPENGINE_SDK=google_appengine python tests/test_indexing.py"
